### ISSUE TITLE
格式化输入文件的小错误【Gaussian】

### ISSUE THREAD

**Issue by huily** [RimoAccelerator/KST48#1]
运行环境：
    系统：windows WSL/Debian10
    量化软件： Gaussian16
    Python版本：Python3.9

不知道是不是我这边的运行环境因素导致，出现以下情况：
984行：LST1 != [] 会提示“DeprecationWarning”
584行、598行：format()函数会报类型不匹配error，分析error发现是从文件读入Geom数据是以字符串str的形式传递，将类型强制转换为float【float(Geom[])】后程序即可正常运行。

**Comment by RimoAccelerator** [comment]
感谢报告。目前代码已更新。
