### ISSUE TITLE
双杂化泛函计算失败

### ISSUE THREAD

**Issue by wangdu817** [RimoAccelerator/KST48#2]
Hi，
非常方便的程序！但从archive读取MP2能量不太稳健，因为能量可能夸行，此外当前的读取格式存在一些问题，读取的能量会出现形如"-227.2191971\\RMSD"的输出，或许应该从'\'处进行第二个split，或者从fchk文件中读取能量更为可靠。
另外今天尝试利用双杂化泛函rev-dsdpbe86（https://www.compchem.me/revdsd-pbep86-functional）进行MECP优化，但是在pre环节gaussian总会报错，pre_A没问题，三重态pre_B有问题：
”  Operation on file out of range.
 FileIO: IOper= 2 IFilNo(1)=  -554 Len=        3225 IPos=           0 Q=   47591755967168
 Error termination in NtrErr:
 NtrErr Called from FileIO.”
这好像由于读取chk文件失败导致的？
附输入文件。
[C2H2O2.txt](https://github.com/RimoAccelerator/KST48/files/14079652/C2H2O2.txt)

**Comment by RimoAccelerator** [comment]
关于换行的问题已经修复。在新的读取方式中，凡是含有/的行都会被汇总在一起，然后读取其中第一个MP2=后的数值。

我重复你报告的双杂化泛函报错的案例，发现是pre_A.log中发现instability后以上述报错结束。此外pre_B.log虽然正常结束，但没有输出双杂化的能量。事实上，我怀疑Gaussian不支持使用双杂化泛函进行stable=opt。这可能是由于存在不稳定性时MP2没有意义，因此Gaussian拒绝执行后续计算。你可以尝试首先使用普通泛函部分获得稳定的波函数，再在双杂化水平下进行读取。

**Comment by wangdu817** [comment]
Hi @RimoAccelerator ,
 在KST48如何能中途终计算并读取稳定波函数进行分析呢？按您说的方法需要在计算完普通泛函后首先中断一次，再读取chk文件，但是每次运行时都会自动覆盖先前的计算结果。

**Comment by RimoAccelerator** [comment]
> Hi @RimoAccelerator , 在KST48如何能中途终计算并读取稳定波函数进行分析呢？按您说的方法需要在计算完普通泛函后首先中断一次，再读取chk文件，但是每次运行时都会自动覆盖先前的计算结果。

先使用普通泛函stable=opt得到a.chk和b.chk，然后使用read模式运行即可。不支持在优化中途去检查波函数稳定性。
